using System.Text.Json.Serialization;
using Polyphony.Configuration;
using Polyphony.Policy;
using Polyphony.Sdlc;

namespace Polyphony;

[JsonSerializable(typeof(RouteResult))]
[JsonSerializable(typeof(ValidateResult))]
[JsonSerializable(typeof(HierarchyResult))]
[JsonSerializable(typeof(HierarchyResult[]))]
[JsonSerializable(typeof(HealthResult))]
[JsonSerializable(typeof(HealthCheckResult))]
[JsonSerializable(typeof(ConfigValidationResult))]
[JsonSerializable(typeof(ConfigValidationDiagnostic[]))]
[JsonSerializable(typeof(PlanDepthGuardResult))]
[JsonSerializable(typeof(PlanNextChildResult))]
[JsonSerializable(typeof(PlannableChild))]
[JsonSerializable(typeof(PlanLoadTypeResult))]
[JsonSerializable(typeof(PlanReviewResult))]
[JsonSerializable(typeof(PolicyLoadResult))]
[JsonSerializable(typeof(PolicyValidateResult))]
[JsonSerializable(typeof(PolicyDomainSnapshot))]
[JsonSerializable(typeof(PolicyConcurrencySnapshot))]
[JsonSerializable(typeof(ResolvedRule))]
[JsonSerializable(typeof(BranchEnsureFeatureResult))]
[JsonSerializable(typeof(BranchEnsureMergeGroupResult))]
[JsonSerializable(typeof(BranchEnsureTaskResult))]
[JsonSerializable(typeof(BranchCheckDepsResult))]
[JsonSerializable(typeof(BlockingItem))]
[JsonSerializable(typeof(BranchCloseScopeResult))]
[JsonSerializable(typeof(ClosedItem))]
[JsonSerializable(typeof(FailedClosure))]
[JsonSerializable(typeof(BranchLoadTreeResult))]
[JsonSerializable(typeof(WorkTree))]
[JsonSerializable(typeof(WorkTreeIssue))]
[JsonSerializable(typeof(WorkTreeTask))]
[JsonSerializable(typeof(MergeGroup))]
[JsonSerializable(typeof(MergeGroupReconciliation))]
[JsonSerializable(typeof(BranchNextTaskResult))]
[JsonSerializable(typeof(PlanSeedChildrenResult))]
[JsonSerializable(typeof(SeedReconciliation))]
[JsonSerializable(typeof(SeedError))]
[JsonSerializable(typeof(PrCreateFeatureResult))]
[JsonSerializable(typeof(PrOpenMergeGroupResult))]
[JsonSerializable(typeof(PrOpenTaskResult))]
[JsonSerializable(typeof(StateDetectResult))]
[JsonSerializable(typeof(ChildrenStateCounts))]
[JsonSerializable(typeof(BranchRouteResult))]
[JsonSerializable(typeof(StatePreflightLiteResult))]
[JsonSerializable(typeof(StatePreflightResult))]
[JsonSerializable(typeof(PreflightCheck))]
[JsonSerializable(typeof(PreflightDetails))]
[JsonSerializable(typeof(ScopeCheckResult))]
[JsonSerializable(typeof(ScopeListResult))]
[JsonSerializable(typeof(ScopeListItem))]
[JsonSerializable(typeof(ScopeMutationResult))]
[JsonSerializable(typeof(RootResolveResult))]
[JsonSerializable(typeof(Requirement))]
[JsonSerializable(typeof(RequirementEdge))]
[JsonSerializable(typeof(RequirementSet))]
[JsonSerializable(typeof(RequirementsDeriveResult))]
[JsonSerializable(typeof(RequirementsInputProvenance))]
[JsonSerializable(typeof(StateNextReadyResult))]
[JsonSerializable(typeof(ResolvedRequirementInputs))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
public sealed partial class PolyphonyJsonContext : JsonSerializerContext;
